# Generated by Django 5.0.6 on 2024-06-17 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='produto',
            fields=[
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('preco', models.DecimalField(decimal_places=2, max_digits=5)),
                ('quantidade', models.IntegerField()),
                ('id_produto', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('data_validade', models.DateField()),
                ('categoria', models.CharField(choices=[('Medicamento', 'Medicamento'), ('Higiene', 'Higiene'), ('Alimento', 'Alimento'), ('Cosmético', 'Cosmético'), ('Outro', 'Outro')], max_length=50)),
                ('prescrição', models.BooleanField()),
                ('nome_fornecedor', models.CharField(max_length=50)),
                ('email_fornecedor', models.EmailField(max_length=254)),
            ],
        ),
    ]
