# Generated by Django 3.2.25 on 2024-05-31 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nome_cliente', models.CharField(max_length=255)),
                ('cpf_cliente', models.CharField(max_length=14, unique=True)),
                ('telefone_cliente', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('nome', models.CharField(max_length=255)),
                ('id_funcionario', models.AutoField(primary_key=True, serialize=False)),
                ('cpf_funcionario', models.CharField(max_length=14, unique=True)),
                ('numero_telefone', models.CharField(max_length=15)),
                ('endereco', models.CharField(max_length=255)),
                ('data_nasc', models.DateField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('data_admissao', models.DateField()),
                ('salario', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Gerente',
            fields=[
                ('id_gerente', models.AutoField(primary_key=True, serialize=False)),
                ('email_gerente', models.EmailField(max_length=254, unique=True)),
                ('senha_gerente', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('nome', models.CharField(max_length=255)),
                ('id_produto', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.TextField()),
                ('preco_produto', models.FloatField()),
                ('data_validade', models.DateField()),
                ('categoria', models.CharField(max_length=255)),
                ('prescricao', models.BooleanField(default=False)),
                ('nome_fornecedor', models.CharField(max_length=255)),
                ('email_fornecedor', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vendas',
            fields=[
                ('id_venda', models.AutoField(primary_key=True, serialize=False)),
                ('data_venda', models.DateField()),
                ('itens_vendidos', models.TextField()),
                ('total_compra', models.FloatField()),
                ('metodo_pagamento', models.CharField(max_length=50)),
                ('nome_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cliente')),
                ('nome_funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.funcionario')),
            ],
        ),
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id_estoque', models.AutoField(primary_key=True, serialize=False)),
                ('qtq_estoque', models.IntegerField()),
                ('qtq_limite', models.IntegerField()),
                ('id_produtoEstoque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.produto')),
            ],
        ),
    ]
