# Generated by Django 5.0.6 on 2024-06-17 16:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='perfil_usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('cpf', models.CharField(max_length=14)),
                ('telefone', models.CharField(max_length=15)),
                ('endereco', models.TextField()),
                ('data_nascimento', models.DateField()),
                ('salario', models.DecimalField(decimal_places=2, max_digits=7)),
                ('cargo', models.CharField(choices=[('gerente', 'Gerente'), ('farmaceutico', 'Farmacêutico'), ('balconista', 'Balconista')], max_length=50)),
                ('data_admissao', models.DateField()),
                ('nome', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
