# Generated by Django 5.0.6 on 2024-06-17 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='vendas',
            fields=[
                ('id_venda', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('data_venda', models.DateField()),
                ('itens_vendidos', models.CharField(max_length=100)),
                ('total_compra', models.FloatField()),
                ('nome_funcionario', models.CharField(max_length=100)),
                ('nome_cliente', models.CharField(max_length=100)),
                ('metodo_pagamento', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ItemVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto_nome', models.CharField(max_length=100)),
                ('produto_id', models.PositiveBigIntegerField()),
                ('quantidade', models.PositiveBigIntegerField()),
                ('preco_venda', models.FloatField()),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendas.vendas')),
            ],
        ),
    ]
